### ISSUE TITLE
Define the API endpoints and their functionalities

### ISSUE THREAD

**Issue by SruthiVeerepall** [WSUCEG-7140/Team-Yellove#11]
The creation of various API endpoints is currently underway. These include the implementation of functionalities such as viewing the menu, adding items to the order, placing the order, tracking the order status, and incorporating custom registration and login features.

**Comment by manibabuveerepalli** [comment]
The development of numerous API endpoints is currently in progress. Viewing the menu, adding products to the order, placing the order, following the order status, and incorporating custom registration and login capabilities are examples of these.
