### ISSUE TITLE
Design the data models and relationships

### ISSUE THREAD

**Issue by SruthiVeerepall** [WSUCEG-7140/Team-Yellove#12]
The necessary tables in the database are created, and dependencies for the required tables are established. This includes tables such as the Registration table, Menu table, and Order table. The Registration table stores user information, such as IDs, usernames, and emails. The Menu table contains details of menu items, such as names, descriptions, and prices. The Order table records customer orders, including order IDs, customer IDs, and item quantities. By establishing dependencies using primary and foreign keys, relationships between these tables are formed for efficient data management.

**Comment by manibabuveerepalli** [comment]
The relevant database tables are built, and dependencies for the required tables are established. This comprises tables like the Registration, Menu, and Order tables. User information such as IDs, usernames, and emails are stored in the Registration table. The Menu table offers information on menu items such as their names, descriptions, and prices. The Order table stores information about customer orders, such as order IDs, customer IDs, and item quantities. Relationships between these tables are built for effective data management by defining dependencies using primary and foreign keys.
