### ISSUE TITLE
API endpoints for Placing an order

### ISSUE THREAD

**Issue by SruthiVeerepall** [WSUCEG-7140/Team-Yellove#21]
### Description:
Implement API endpoints for placing an order in the restaurant management project. These endpoints will allow clients to create and submit orders for food or beverages, facilitating seamless transactions and order processing.

### Key Steps:

- **API Endpoint Design:** Define the API endpoint structure for placing an order. Determine the appropriate HTTP method, request/response formats, and endpoint path that align with RESTful principles or any specific API design specifications.

- **Request Validation:** Implement validation logic to ensure the integrity and validity of the order request payload. Validate the incoming data, including items, quantities, customer information, payment details, and any other relevant details. Handle error cases and provide meaningful error responses.

- **Order Creation**: Develop the logic to create a new order based on the provided order details. Generate a unique order ID, associate it with the customer, and store the order in the database or any other persistent storage. Handle any necessary calculations, such as subtotal, taxes, and total amount.

- **- Payment Processing: Integrate payment processing functionality to handle the payment for the order. Validate payment information, such as credit card details or any other payment method used. Implement error handling for payment failures or declined transactions.**

**Comment by tejaswini-minupala** [comment]
The code looks good and its show us how to implement API endpoints for placing order in the restaurant management system.
